services:
  web:
    build:
      context: ./configs/web
    volumes:
      - $WEB_LOG_DIR:/var/log/apache2
      - $WEB_SOURCE_PATH:/var/www/html/sportify
      - $SSL_CERT_PATH:/etc/ssl/certs/certificate.crt
      - $SSL_PRIVATE_PATH:/etc/ssl/private/private.key
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: apache_config
        target: /etc/apache2/sites-available/000-default.conf
      - source: php
        target: /usr/local/etc/php/php.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 2
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DB: $DB_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - $DB_PATH:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - $REDIS_PATH:/data

  mailhog:
    image: mailhog/mailhog
    healthcheck:
      test: ["CMD", 'nc', '-z', 'localhost', '8025']
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"

configs:
  php:
    file: $PHP_CONFIG_PATH
  apache_config:
    file: $WEB_CONFIG_PATH