version: '3.9'

services:
  web:
    build:
      context: ./configs/web
    volumes:
      - $WEB_SOURCE_PATH:/var/www/html/sportify
    ports:
      - "80:80"
    configs:
      - source: apache_config
        target: /etc/apache2/sites-available/000-default.conf
      - source: php
        target: /usr/local/etc/php/php.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 2
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DB: $DB_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - $DB_PATH:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]

configs:
  php:
    file: $PHP_CONFIG_PATH
  apache_config:
    file: $WEB_CONFIG_PATH