<?php

namespace frontend\controllers;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AjaxController extends  Controller
{

    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['header'],
                'rules' => [
                    [
                        'actions' => ['header'],
                        'allow' => true,
                        'roles' => ['?', '&']
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'header' => ['get'],
                ],
            ],
        ];

    }

    public function actions(): array
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionHeader($headerView): string
    {
        return $this->renderPartial('@frontend/Views/layouts/_header' . $headerView);
    }

}